import { Router, Request, Response } from 'express';
import crypto from 'crypto';
import {
  OutputSource,
  OutputField,
  DiscoveryResult,
  SourceRelationship,
  JoinValidationResult,
  FormulaFunctionDoc,
  CustomMetricDefinition,
  FormulaValidationResult,
  ReportDefinition,
  ReportTemplate,
  SemanticOutputMapping,
  ReportHealthItem,
  ReportExecutionLog,
  CopilotReportPlan,
  PivotConfig,
  ChartConfig
} from '../types/phase25OutputStudio';

export const outputStudioRouter = Router();

// ==========================================
// MOCK & DISCOVERY REPOSITORY DATA
// ==========================================

const SAMPLE_FIELDS_VOUCHERS: OutputField[] = [
  { fieldId: 'v_id', displayName: 'Voucher ID', sourceName: 'Vouchers', type: 'Text', category: 'Identity', description: 'Internal unique GUID/master ID of the voucher', availability: 'Available', canonicalField: 'Voucher.Id', sourceField: '$GUID', exampleValue: 'e9b2-33a1-9481' },
  { fieldId: 'v_date', displayName: 'Date', sourceName: 'Vouchers', type: 'Date', category: 'Date', description: 'Transaction posting date', availability: 'Available', canonicalField: 'Voucher.Date', sourceField: '$Date', exampleValue: '2026-03-31' },
  { fieldId: 'v_no', displayName: 'Voucher Number', sourceName: 'Vouchers', type: 'Text', category: 'Voucher', description: 'Sequential voucher number generated by Tally', availability: 'Available', canonicalField: 'Voucher.Number', sourceField: '$VoucherNumber', exampleValue: 'SAL-2026-0881' },
  { fieldId: 'v_type', displayName: 'Voucher Type', sourceName: 'Vouchers', type: 'Text', category: 'Voucher', description: 'Type of voucher (Sales, Purchase, Journal, Payment, Receipt)', availability: 'Available', canonicalField: 'Voucher.Type', sourceField: '$VoucherTypeName', exampleValue: 'Sales' },
  { fieldId: 'v_party', displayName: 'Party Name', sourceName: 'Vouchers', type: 'Text', category: 'Party', description: 'Ledger name of primary customer/supplier', availability: 'Available', canonicalField: 'Voucher.PartyLedger', sourceField: '$PartyLedgerName', exampleValue: 'Acme Corp Infotech Pvt Ltd' },
  { fieldId: 'v_amount', displayName: 'Total Amount', sourceName: 'Vouchers', type: 'Currency', category: 'Amount', description: 'Gross transaction amount in base currency', availability: 'Available', canonicalField: 'Voucher.Amount', sourceField: '$Amount', exampleValue: '124500.00' },
  { fieldId: 'v_tax_amt', displayName: 'Tax Amount', sourceName: 'Vouchers', type: 'Currency', category: 'Tax', description: 'Cumulative tax lines (GST/TDS)', availability: 'Available', canonicalField: 'Voucher.TaxAmount', sourceField: '$LedgerTaxAmount', exampleValue: '22410.00' },
  { fieldId: 'v_net_amt', displayName: 'Net Amount', sourceName: 'Vouchers', type: 'Currency', category: 'Amount', description: 'Net total including statutory charges', availability: 'Available', canonicalField: 'Voucher.NetAmount', sourceField: '$NetAmount', exampleValue: '146910.00' },
  { fieldId: 'v_narration', displayName: 'Narration', sourceName: 'Vouchers', type: 'Text', category: 'Reference', description: 'Voucher remarks and user notes', availability: 'Available', canonicalField: 'Voucher.Narration', sourceField: '$Narration', exampleValue: 'Enterprise Cloud License renewal FY26-27' },
  { fieldId: 'v_cost_centre', displayName: 'Cost Centre', sourceName: 'Vouchers', type: 'Text', category: 'Location', description: 'Assigned cost center or department', availability: 'Available', canonicalField: 'Voucher.CostCentre', sourceField: '$CostCentreName', exampleValue: 'South Enterprise Tech' },
  { fieldId: 'v_gstin', displayName: 'Party GSTIN', sourceName: 'Vouchers', type: 'Text', category: 'Tax', description: '15-digit GST Identification Number of party', availability: 'Available', canonicalField: 'Voucher.PartyGSTIN', sourceField: '$PartyGSTIN', exampleValue: '29ABCDE1234F1Z5' },
  { fieldId: 'v_state', displayName: 'Place of Supply', sourceName: 'Vouchers', type: 'Text', category: 'Location', description: 'State of supply for GST jurisdiction', availability: 'Available', canonicalField: 'Voucher.StateName', sourceField: '$StateName', exampleValue: 'Karnataka' },
];

const SAMPLE_FIELDS_LEDGERS: OutputField[] = [
  { fieldId: 'l_id', displayName: 'Ledger ID', sourceName: 'Ledgers', type: 'Text', category: 'Identity', description: 'Unique ledger master key', availability: 'Available', canonicalField: 'Ledger.Id', sourceField: '$MasterID', exampleValue: 'LED-00441' },
  { fieldId: 'l_name', displayName: 'Ledger Name', sourceName: 'Ledgers', type: 'Text', category: 'Ledger', description: 'Chart of accounts ledger name', availability: 'Available', canonicalField: 'Ledger.Name', sourceField: '$Name', exampleValue: 'HDFC Bank Operative A/c' },
  { fieldId: 'l_parent', displayName: 'Parent Group', sourceName: 'Ledgers', type: 'Text', category: 'Ledger', description: 'Primary or sub-group in Chart of Accounts', availability: 'Available', canonicalField: 'Ledger.ParentGroup', sourceField: '$Parent', exampleValue: 'Bank Accounts' },
  { fieldId: 'l_op_bal', displayName: 'Opening Balance', sourceName: 'Ledgers', type: 'Currency', category: 'Amount', description: 'Opening balance at start of FY', availability: 'Available', canonicalField: 'Ledger.OpeningBalance', sourceField: '$OpeningBalance', exampleValue: '4500000.00' },
  { fieldId: 'l_cl_bal', displayName: 'Closing Balance', sourceName: 'Ledgers', type: 'Currency', category: 'Amount', description: 'Current closing ledger balance', availability: 'Available', canonicalField: 'Ledger.ClosingBalance', sourceField: '$ClosingBalance', exampleValue: '5820400.00' },
  { fieldId: 'l_credit_period', displayName: 'Credit Period (Days)', sourceName: 'Ledgers', type: 'Integer', category: 'Reference', description: 'Bill-wise allowed payment credit period', availability: 'Available', canonicalField: 'Ledger.CreditPeriod', sourceField: '$BillCreditPeriod', exampleValue: '30' },
  { fieldId: 'l_credit_limit', displayName: 'Credit Limit', sourceName: 'Ledgers', type: 'Currency', category: 'Amount', description: 'Maximum approved outstanding credit', availability: 'Available', canonicalField: 'Ledger.CreditLimit', sourceField: '$CreditLimit', exampleValue: '2000000.00' },
];

const SAMPLE_FIELDS_STOCK: OutputField[] = [
  { fieldId: 's_id', displayName: 'Item ID', sourceName: 'Stock Items', type: 'Text', category: 'Identity', description: 'Stock master unique ID', availability: 'Available', canonicalField: 'StockItem.Id', sourceField: '$MasterID', exampleValue: 'STK-0091' },
  { fieldId: 's_name', displayName: 'Stock Item Name', sourceName: 'Stock Items', type: 'Text', category: 'Inventory', description: 'Inventory SKU name', availability: 'Available', canonicalField: 'StockItem.Name', sourceField: '$Name', exampleValue: 'Industrial IoT Controller X4' },
  { fieldId: 's_group', displayName: 'Stock Group', sourceName: 'Stock Items', type: 'Text', category: 'Inventory', description: 'Category grouping of inventory', availability: 'Available', canonicalField: 'StockItem.Group', sourceField: '$Parent', exampleValue: 'Hardware Automation' },
  { fieldId: 's_uom', displayName: 'Base Unit', sourceName: 'Stock Items', type: 'Text', category: 'Quantity', description: 'Unit of measure (Nos, Pcs, Kgs, Mtr)', availability: 'Available', canonicalField: 'StockItem.UOM', sourceField: '$BaseUnits', exampleValue: 'Nos' },
  { fieldId: 's_qty_on_hand', displayName: 'Quantity on Hand', sourceName: 'Stock Items', type: 'Decimal', category: 'Quantity', description: 'Current physical inventory in godowns', availability: 'Available', canonicalField: 'StockItem.QtyOnHand', sourceField: '$ClosingBalance', exampleValue: '480.00' },
  { fieldId: 's_standard_cost', displayName: 'Standard Cost', sourceName: 'Stock Items', type: 'Currency', category: 'Amount', description: 'Average inventory purchase valuation', availability: 'Available', canonicalField: 'StockItem.StandardCost', sourceField: '$StandardCost', exampleValue: '12500.00' },
  { fieldId: 's_selling_price', displayName: 'Selling Price', sourceName: 'Stock Items', type: 'Currency', category: 'Amount', description: 'Default list price for sales invoices', availability: 'Available', canonicalField: 'StockItem.SellingPrice', sourceField: '$StandardPrice', exampleValue: '18500.00' },
  { fieldId: 's_hsn', displayName: 'HSN / SAC Code', sourceName: 'Stock Items', type: 'Text', category: 'Tax', description: 'Harmonized System Nomenclature code for GST', availability: 'Available', canonicalField: 'StockItem.HSN', sourceField: '$HSNCode', exampleValue: '85371000' },
  { fieldId: 's_reorder_level', displayName: 'Reorder Level', sourceName: 'Stock Items', type: 'Decimal', category: 'Quantity', description: 'Threshold triggering replenishment alert', availability: 'Available', canonicalField: 'StockItem.ReorderLevel', sourceField: '$ReorderLevel', exampleValue: '100.00' },
];

const STANDARD_SOURCES_METADATA: { name: string; type: string; desc: string; count: number; dims: number; measures: number; fields: OutputField[] }[] = [
  { name: 'Companies', type: 'Master', desc: 'Active Tally multi-company directory and licensing metadata', count: 4, dims: 6, measures: 2, fields: SAMPLE_FIELDS_LEDGERS.slice(0, 3) },
  { name: 'Groups', type: 'Master', desc: 'Chart of Accounts classification tree and hierarchy', count: 28, dims: 4, measures: 2, fields: SAMPLE_FIELDS_LEDGERS.slice(1, 4) },
  { name: 'Ledgers', type: 'Master', desc: 'General ledger accounts, balances, credit terms, and GST details', count: 184, dims: 8, measures: 4, fields: SAMPLE_FIELDS_LEDGERS },
  { name: 'Stock Items', type: 'Inventory', desc: 'Item catalog, stock groups, pricing, batches, and reorder levels', count: 340, dims: 9, measures: 5, fields: SAMPLE_FIELDS_STOCK },
  { name: 'Stock Groups', type: 'Inventory', desc: 'Hierarchical product groupings and category structures', count: 18, dims: 4, measures: 2, fields: SAMPLE_FIELDS_STOCK.slice(0, 4) },
  { name: 'Units', type: 'Inventory', desc: 'Simple & compound units of measure definitions', count: 8, dims: 3, measures: 1, fields: SAMPLE_FIELDS_STOCK.slice(3, 5) },
  { name: 'Godowns', type: 'Inventory', desc: 'Warehouse locations, transit storage, and racks', count: 6, dims: 4, measures: 2, fields: SAMPLE_FIELDS_STOCK.slice(0, 3) },
  { name: 'Batches', type: 'Inventory', desc: 'Manufacturing batch numbers, expiry dates, and lot tracking', count: 72, dims: 6, measures: 3, fields: SAMPLE_FIELDS_STOCK.slice(0, 4) },
  { name: 'Vouchers', type: 'Transaction', desc: 'Transactional register (Sales, Purchase, Receipts, Payments, Journals)', count: 24800, dims: 12, measures: 6, fields: SAMPLE_FIELDS_VOUCHERS },
  { name: 'Voucher Types', type: 'Master', desc: 'Configured voucher classes and numbering sequences', count: 14, dims: 5, measures: 1, fields: SAMPLE_FIELDS_VOUCHERS.slice(2, 5) },
  { name: 'Cost Centres', type: 'Master', desc: 'Departmental, project, and branch profit/cost centers', count: 12, dims: 4, measures: 3, fields: SAMPLE_FIELDS_VOUCHERS.slice(8, 11) },
  { name: 'Employees', type: 'Payroll', desc: 'Staff directory, designations, and payroll master records', count: 65, dims: 7, measures: 2, fields: SAMPLE_FIELDS_LEDGERS.slice(0, 3) },
  { name: 'Payroll', type: 'Payroll', desc: 'Monthly attendance, salary slips, deductions, and PF/ESI calculations', count: 780, dims: 8, measures: 6, fields: SAMPLE_FIELDS_VOUCHERS.slice(0, 6) },
  { name: 'Outstanding', type: 'Statutory', desc: 'Receivables and payables ageing analysis and bill overdue schedules', count: 420, dims: 7, measures: 4, fields: SAMPLE_FIELDS_VOUCHERS.slice(3, 8) },
  { name: 'GST', type: 'Statutory', desc: 'GSTR-1, GSTR-3B tax components, HSN summaries, and ITC verification', count: 1250, dims: 10, measures: 6, fields: SAMPLE_FIELDS_VOUCHERS.slice(5, 12) },
  { name: 'Day Book', type: 'Report', desc: 'Chronological multi-voucher journal log with opening and closing cash', count: 3200, dims: 8, measures: 4, fields: SAMPLE_FIELDS_VOUCHERS.slice(0, 8) },
  { name: 'Balance Sheet', type: 'Financial', desc: 'Standard double-entry Statement of Assets and Liabilities', count: 85, dims: 5, measures: 4, fields: SAMPLE_FIELDS_LEDGERS.slice(1, 6) },
  { name: 'Profit & Loss', type: 'Financial', desc: 'Trading and income statement with revenue, COGS, and overheads', count: 95, dims: 5, measures: 4, fields: SAMPLE_FIELDS_LEDGERS.slice(1, 6) },
  { name: 'Trial Balance', type: 'Financial', desc: 'Periodic closing debit/credit trial balance across all ledger groups', count: 184, dims: 6, measures: 4, fields: SAMPLE_FIELDS_LEDGERS.slice(1, 6) },
  { name: 'Cash Flow', type: 'Financial', desc: 'Operating, investing, and financing cash movements', count: 48, dims: 4, measures: 3, fields: SAMPLE_FIELDS_LEDGERS.slice(2, 6) },
  { name: 'Fund Flow', type: 'Financial', desc: 'Sources and applications of working capital', count: 42, dims: 4, measures: 3, fields: SAMPLE_FIELDS_LEDGERS.slice(2, 6) },
  { name: 'Ratio Reports', type: 'Analytical', desc: 'Liquidity, solvency, turnover, and profitability financial ratios', count: 24, dims: 3, measures: 5, fields: SAMPLE_FIELDS_LEDGERS.slice(3, 7) },
  { name: 'Custom Reports', type: 'Custom', desc: 'User-designed and cloned analytical reports', count: 8, dims: 6, measures: 4, fields: SAMPLE_FIELDS_VOUCHERS.slice(0, 6) },
  { name: 'Custom TDL Outputs', type: 'TDL', desc: 'Exposed TDL collection definitions, custom fields, and extensions', count: 15, dims: 7, measures: 3, fields: SAMPLE_FIELDS_VOUCHERS.slice(0, 8) }
];

let globalDiscoveryCache: DiscoveryResult | null = null;
let globalDiscoveryTimestamp: number = 0;
const CACHE_TTL_MS = 15 * 60 * 1000; // 15 mins

// In-Memory Reports Repository
let savedReports: ReportDefinition[] = [
  {
    id: 'rep-001',
    name: 'Executive Sales & Receivables Intelligence',
    description: 'Consolidated overview of top customer billings, state tax distributions, and ageing receivables.',
    type: 'Analytical',
    owner: 'Arjun Mehta (VP Finance)',
    createdBy: 'Arjun Mehta',
    scope: 'Global',
    status: 'Published',
    version: 3,
    companyScope: ['ALL'],
    tags: ['Sales', 'Finance', 'Management'],
    primarySourceId: 'Vouchers',
    parameters: [
      { id: 'p_from', key: 'fromDate', label: 'From Date', type: 'Date', defaultValue: '2026-01-01', isRequired: true },
      { id: 'p_to', key: 'toDate', label: 'To Date', type: 'Date', defaultValue: '2026-03-31', isRequired: true },
      { id: 'p_vtype', key: 'voucherType', label: 'Voucher Type', type: 'Select', defaultValue: 'Sales', options: [{ label: 'Sales', value: 'Sales' }, { label: 'Purchase', value: 'Purchase' }, { label: 'All', value: 'All' }], isRequired: false }
    ],
    globalFilters: [
      {
        id: 'gf_1',
        logicalOperator: 'AND',
        conditions: [
          { id: 'c_1', fieldId: 'v_type', operator: '=', value: 'Sales' },
          { id: 'c_2', fieldId: 'v_amount', operator: '>', value: '5000' }
        ]
      }
    ],
    groupings: [{ fieldId: 'v_party', showSubtotals: true }],
    columns: [
      { fieldId: 'v_date', label: 'Invoice Date', alignment: 'center', format: 'Plain', dateFormat: 'DD/MM/YYYY', isVisible: true },
      { fieldId: 'v_no', label: 'Invoice #', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 'v_party', label: 'Customer / Party', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 'v_amount', label: 'Gross Amount', alignment: 'right', format: 'Indian', currencySymbol: '₹', decimals: 2, isVisible: true, aggregation: 'SUM' },
      { fieldId: 'v_tax_amt', label: 'GST Tax', alignment: 'right', format: 'Indian', currencySymbol: '₹', decimals: 2, isVisible: true, aggregation: 'SUM' },
      { fieldId: 'v_net_amt', label: 'Net Billing', alignment: 'right', format: 'Indian', currencySymbol: '₹', decimals: 2, isVisible: true, aggregation: 'SUM', conditionalFormatting: [{ condition: '>', value: '100000', action: 'Highlight', colorTag: 'emerald' }] }
    ],
    calculatedColumns: [
      { id: 'cc_1', name: 'Tax Ratio %', formula: '(v_tax_amt / v_amount) * 100', type: 'Percentage' }
    ],
    pivotConfig: {
      rowFields: ['v_party'],
      columnFields: ['v_state'],
      valueFields: [{ fieldId: 'v_net_amt', aggregation: 'SUM', label: 'Net Amount' }],
      showSubtotals: true,
      showGrandTotals: true,
      topN: 10
    },
    chartConfig: {
      chartType: 'Bar',
      title: 'Top 10 Customers by Net Invoicing',
      xAxisField: 'v_party',
      yAxisFields: ['v_net_amt'],
      aggregation: 'SUM',
      showLegend: true
    },
    showGrandTotal: true,
    pages: [
      {
        id: 'pg_1',
        title: 'Executive Dashboard',
        order: 1,
        widgets: [
          { id: 'w_1', title: 'Top Invoices Table', type: 'Table', sourceId: 'Vouchers', columns: [], filters: [], gridPosition: { x: 0, y: 0, w: 12, h: 6 } },
          { id: 'w_2', title: 'Revenue by Customer', type: 'Chart', sourceId: 'Vouchers', columns: [], filters: [], gridPosition: { x: 0, y: 6, w: 6, h: 6 } },
          { id: 'w_3', title: 'State-wise Pivot', type: 'Pivot', sourceId: 'Vouchers', columns: [], filters: [], gridPosition: { x: 6, y: 6, w: 6, h: 6 } }
        ]
      }
    ],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-07T14:30:00Z'
  },
  {
    id: 'rep-002',
    name: 'Stock Valuation & Reorder Threshold Monitor',
    description: 'SKU-level inventory analysis highlighting critical stocks below reorder level and valuation breakdown.',
    type: 'Operational',
    owner: 'Pooja Nair (Supply Chain)',
    createdBy: 'Pooja Nair',
    scope: 'Team',
    status: 'Published',
    version: 1,
    companyScope: ['ALL'],
    tags: ['Inventory', 'Warehouse', 'Operations'],
    primarySourceId: 'Stock Items',
    parameters: [
      { id: 'p_group', key: 'stockGroup', label: 'Stock Group', type: 'Select', defaultValue: 'All', options: [{ label: 'All', value: 'All' }, { label: 'Hardware Automation', value: 'Hardware Automation' }], isRequired: false }
    ],
    globalFilters: [],
    groupings: [{ fieldId: 's_group', showSubtotals: true }],
    columns: [
      { fieldId: 's_id', label: 'SKU Code', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 's_name', label: 'Item Name', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 's_group', label: 'Category', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 's_qty_on_hand', label: 'Stock Qty', alignment: 'right', format: 'Indian', decimals: 2, isVisible: true, aggregation: 'SUM' },
      { fieldId: 's_standard_cost', label: 'Unit Cost', alignment: 'right', format: 'Indian', currencySymbol: '₹', decimals: 2, isVisible: true },
      { fieldId: 's_selling_price', label: 'List Price', alignment: 'right', format: 'Indian', currencySymbol: '₹', decimals: 2, isVisible: true },
      { fieldId: 's_reorder_level', label: 'Min Level', alignment: 'right', format: 'Indian', decimals: 2, isVisible: true }
    ],
    calculatedColumns: [
      { id: 'cc_val', name: 'Inventory Asset Value', formula: 's_qty_on_hand * s_standard_cost', type: 'Currency' }
    ],
    showGrandTotal: true,
    pages: [],
    createdAt: '2026-03-02T11:20:00Z',
    updatedAt: '2026-03-04T09:15:00Z'
  },
  {
    id: 'rep-003',
    name: 'GST Compliance & HSN Tax Distribution',
    description: 'Comprehensive tax audit report comparing GSTR-1 outward tax liability against voucher ledgers.',
    type: 'Reconciliation',
    owner: 'Rohan Sharma (Tax Lead)',
    createdBy: 'Rohan Sharma',
    scope: 'Company',
    status: 'Published',
    version: 2,
    companyScope: ['comp-101'],
    tags: ['GST', 'Statutory', 'Audit'],
    primarySourceId: 'GST',
    parameters: [],
    globalFilters: [],
    groupings: [],
    columns: [
      { fieldId: 'v_no', label: 'Voucher Number', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 'v_party', label: 'Party Name', alignment: 'left', format: 'Plain', isVisible: true },
      { fieldId: 'v_gstin', label: 'GSTIN', alignment: 'center', format: 'Plain', isVisible: true },
      { fieldId: 'v_amount', label: 'Taxable Value', alignment: 'right', format: 'Indian', currencySymbol: '₹', isVisible: true, aggregation: 'SUM' },
      { fieldId: 'v_tax_amt', label: 'GST Amount', alignment: 'right', format: 'Indian', currencySymbol: '₹', isVisible: true, aggregation: 'SUM' }
    ],
    calculatedColumns: [],
    showGrandTotal: true,
    pages: [],
    createdAt: '2026-03-03T16:00:00Z',
    updatedAt: '2026-03-06T18:00:00Z'
  }
];

let customMetrics: CustomMetricDefinition[] = [
  {
    metricId: 'm-001',
    name: 'Effective Tax Rate %',
    formula: 'COALESCE((v_tax_amt / v_amount) * 100, 0)',
    sourceId: 'Vouchers',
    version: 1,
    createdBy: 'Arjun Mehta',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    isAccountingStandardVerified: true,
    userLabel: 'Effective Tax Rate',
    lineage: {
      metric: 'Effective Tax Rate %',
      formula: '(v_tax_amt / v_amount) * 100',
      fields: ['v_tax_amt', 'v_amount'],
      dataset: 'Vouchers',
      source: 'TallyPrime Enterprise (Local Engine)'
    }
  },
  {
    metricId: 'm-002',
    name: 'Inventory Potential Revenue',
    formula: 's_qty_on_hand * s_selling_price',
    sourceId: 'Stock Items',
    version: 1,
    createdBy: 'Pooja Nair',
    createdAt: '2026-03-02T11:00:00Z',
    updatedAt: '2026-03-02T11:00:00Z',
    isAccountingStandardVerified: false,
    userLabel: 'Custom Inventory Potential Value',
    lineage: {
      metric: 'Inventory Potential Revenue',
      formula: 's_qty_on_hand * s_selling_price',
      fields: ['s_qty_on_hand', 's_selling_price'],
      dataset: 'Stock Items',
      source: 'Tally Stock Registry'
    }
  }
];

const BUILT_IN_TEMPLATES: ReportTemplate[] = [
  {
    templateId: 'tpl-daybook',
    name: 'Standard Day Book Journal',
    category: 'Finance',
    description: 'Chronological recording of daily transactions, vouchers, narration, and debit/credit sums.',
    requiredSources: ['Day Book', 'Vouchers'],
    requiredFields: ['v_date', 'v_no', 'v_party', 'v_amount'],
    isSupported: true,
    version: '1.0.0',
    definition: {
      name: 'Day Book Ledger Register',
      type: 'Standard',
      tags: ['Finance', 'Day Book'],
      primarySourceId: 'Vouchers'
    }
  },
  {
    templateId: 'tpl-trialbalance',
    name: 'Hierarchical Trial Balance',
    category: 'Finance',
    description: 'Double-entry debit and credit group summation verifying arithmetic equilibrium.',
    requiredSources: ['Trial Balance', 'Ledgers'],
    requiredFields: ['l_name', 'l_parent', 'l_op_bal', 'l_cl_bal'],
    isSupported: true,
    version: '1.0.0',
    definition: {
      name: 'Group-wise Trial Balance',
      type: 'Standard',
      tags: ['Finance', 'Trial Balance'],
      primarySourceId: 'Ledgers'
    }
  },
  {
    templateId: 'tpl-outstanding',
    name: 'Customer Receivables & Ageing Schedule',
    category: 'Management',
    description: 'Overdue bill tracking with 0-30, 31-60, 61-90, 90+ day ageing buckets.',
    requiredSources: ['Outstanding', 'Vouchers'],
    requiredFields: ['v_party', 'v_date', 'v_amount'],
    isSupported: true,
    version: '1.0.0',
    definition: {
      name: 'Receivables Ageing Analysis',
      type: 'Analytical',
      tags: ['Sales', 'Outstanding'],
      primarySourceId: 'Vouchers'
    }
  },
  {
    templateId: 'tpl-salesregister',
    name: 'Sales Register with GST Breakdown',
    category: 'Sales',
    description: 'Monthly and party-wise sales invoices detailing taxable amount, CGST, SGST, IGST, and total billing.',
    requiredSources: ['Vouchers', 'GST'],
    requiredFields: ['v_date', 'v_no', 'v_party', 'v_amount', 'v_tax_amt', 'v_net_amt'],
    isSupported: true,
    version: '1.0.0',
    definition: {
      name: 'Sales Register & Tax Split',
      type: 'Operational',
      tags: ['Sales', 'GST'],
      primarySourceId: 'Vouchers'
    }
  },
  {
    templateId: 'tpl-stocksummary',
    name: 'Inventory Valuation & Fast-Moving Items',
    category: 'Inventory',
    description: 'Group-wise stock item quantities, average cost valuation, and inventory holding value.',
    requiredSources: ['Stock Items', 'Stock Groups'],
    requiredFields: ['s_name', 's_group', 's_qty_on_hand', 's_standard_cost'],
    isSupported: true,
    version: '1.0.0',
    definition: {
      name: 'Inventory Valuation Summary',
      type: 'Operational',
      tags: ['Inventory'],
      primarySourceId: 'Stock Items'
    }
  }
];

const SOURCE_RELATIONSHIPS: SourceRelationship[] = [
  {
    id: 'rel-1',
    fromSource: 'Companies',
    fromKey: 'Company.Id',
    toSource: 'Ledgers',
    toKey: 'Ledger.CompanyId',
    type: 'One-to-Many',
    isValidated: true,
    hasManyToManyRisk: false,
    sampleMatchesCount: 184,
    description: 'Each connected Company possesses a dedicated Chart of Accounts (Ledgers).'
  },
  {
    id: 'rel-2',
    fromSource: 'Ledgers',
    fromKey: 'Ledger.Name',
    toSource: 'Vouchers',
    toKey: 'Voucher.PartyLedger',
    type: 'One-to-Many',
    isValidated: true,
    hasManyToManyRisk: false,
    sampleMatchesCount: 24800,
    description: 'Party Ledger maps to primary debit/credit entry on transactional Vouchers.'
  },
  {
    id: 'rel-3',
    fromSource: 'Stock Items',
    fromKey: 'StockItem.Name',
    toSource: 'Vouchers',
    toKey: 'Voucher.InventoryLine.ItemName',
    type: 'One-to-Many',
    isValidated: true,
    hasManyToManyRisk: false,
    sampleMatchesCount: 18400,
    description: 'Stock Item master links to itemized billing lines inside invoices.'
  },
  {
    id: 'rel-4',
    fromSource: 'Stock Items',
    fromKey: 'StockItem.Group',
    toSource: 'Stock Groups',
    toKey: 'StockGroup.Name',
    type: 'Many-to-One',
    isValidated: true,
    hasManyToManyRisk: false,
    sampleMatchesCount: 340,
    description: 'Each Stock Item belongs to a categorized Stock Group.'
  }
];

let executionHistory: ReportExecutionLog[] = [
  {
    id: 'exec-101',
    reportId: 'rep-001',
    reportName: 'Executive Sales & Receivables Intelligence',
    companyId: 'comp-101',
    companyName: 'Acme Enterprise Ltd (HO)',
    executionTimeMs: 142,
    rowsCount: 1250,
    state: 'Completed',
    executedBy: 'Arjun Mehta',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    isCached: true
  },
  {
    id: 'exec-102',
    reportId: 'rep-002',
    reportName: 'Stock Valuation & Reorder Threshold Monitor',
    companyId: 'comp-101',
    companyName: 'Acme Enterprise Ltd (HO)',
    executionTimeMs: 88,
    rowsCount: 340,
    state: 'Completed',
    executedBy: 'Pooja Nair',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    isCached: false
  }
];

// ==========================================
// 1. DISCOVERY ENGINE (IOutputDiscoveryEngine)
// ==========================================

outputStudioRouter.get('/discover', (req: Request, res: Response) => {
  const forceRefresh = req.query.refresh === 'true';
  const now = Date.now();

  if (!forceRefresh && globalDiscoveryCache && now - globalDiscoveryTimestamp < CACHE_TTL_MS) {
    return res.json({
      success: true,
      data: globalDiscoveryCache
    });
  }

  const sources: OutputSource[] = STANDARD_SOURCES_METADATA.map((meta, idx) => {
    let status = 'Available';
    if (meta.type === 'TDL' && idx % 3 === 0) status = 'Requires Configuration';
    if (meta.name === 'Ratio Reports') status = 'Available';

    return {
      sourceId: meta.name,
      sourceName: meta.name,
      sourceType: meta.type,
      description: meta.desc,
      companyId: 'comp-101',
      connectionId: 'conn-local-9000',
      status: status as any,
      recordCount: meta.count,
      dimensionsCount: meta.dims,
      measuresCount: meta.measures,
      fields: meta.fields,
      lastDiscovered: new Date().toISOString(),
      adapterVersion: '4.1.0-Enterprise',
      isTDL: meta.type === 'TDL'
    };
  });

  const discoveryResult: DiscoveryResult = {
    companyId: 'comp-101',
    companyName: 'Acme Enterprise Ltd (HQ - Mumbai)',
    connectionId: 'conn-local-9000',
    timestamp: new Date().toISOString(),
    adapterVersion: '4.1.0-Enterprise',
    tallyVersion: 'TallyPrime Release 4.1 (64-Bit)',
    sources,
    totalAvailableSources: sources.filter((s) => s.status === 'Available').length,
    totalFieldsDiscovered: sources.reduce((acc, s) => acc + s.fields.length, 0),
    isLiveConnection: true,
    isCached: false
  };

  globalDiscoveryCache = discoveryResult;
  globalDiscoveryTimestamp = now;

  return res.json({
    success: true,
    data: discoveryResult
  });
});

// ==========================================
// 2. DATA & FIELD CATALOG
// ==========================================

outputStudioRouter.get('/catalog', (req: Request, res: Response) => {
  const { source, category, search, type, onlyFavorites } = req.query;

  let allFields: OutputField[] = [];
  STANDARD_SOURCES_METADATA.forEach((src) => {
    allFields.push(...src.fields);
  });

  // Deduplicate by fieldId
  const fieldMap = new Map<string, OutputField>();
  allFields.forEach((f) => {
    if (!fieldMap.has(f.fieldId)) {
      fieldMap.set(f.fieldId, { ...f });
    }
  });

  let fields = Array.from(fieldMap.values());

  if (source && source !== 'All') {
    fields = fields.filter((f) => f.sourceName.toLowerCase() === String(source).toLowerCase());
  }
  if (category && category !== 'All') {
    fields = fields.filter((f) => f.category.toLowerCase() === String(category).toLowerCase());
  }
  if (type && type !== 'All') {
    fields = fields.filter((f) => f.type.toLowerCase() === String(type).toLowerCase());
  }
  if (onlyFavorites === 'true') {
    fields = fields.filter((f) => f.isFavorite);
  }
  if (search) {
    const q = String(search).toLowerCase();
    fields = fields.filter(
      (f) =>
        f.displayName.toLowerCase().includes(q) ||
        f.fieldId.toLowerCase().includes(q) ||
        f.description.toLowerCase().includes(q) ||
        (f.canonicalField && f.canonicalField.toLowerCase().includes(q))
    );
  }

  res.json({
    success: true,
    data: {
      totalFields: fields.length,
      fields,
      sourcesSummary: STANDARD_SOURCES_METADATA.map((s) => ({
        name: s.name,
        type: s.type,
        fieldCount: s.fields.length,
        recordCount: s.count
      }))
    }
  });
});

// ==========================================
// 3. SOURCE RELATIONSHIPS & JOIN ENGINE (IJoinEngine)
// ==========================================

outputStudioRouter.get('/relationships', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      relationships: SOURCE_RELATIONSHIPS
    }
  });
});

outputStudioRouter.post('/joins/validate', (req: Request, res: Response) => {
  const { fromSource, fromKey, toSource, toKey } = req.body;

  if (!fromSource || !toSource || !fromKey || !toKey) {
    return res.status(400).json({
      success: false,
      error: 'Missing required join keys or source names.'
    });
  }

  // Detect relationship type and simulate validation
  let detectedType = 'One-to-Many';
  let warning: string | undefined = undefined;
  let hasManyToMany = false;

  if (fromSource === toSource) {
    detectedType = 'One-to-One';
  } else if (fromKey.includes('Id') && toKey.includes('Id')) {
    detectedType = 'One-to-One';
  } else if (fromKey.includes('Party') && toKey.includes('State')) {
    detectedType = 'Many-to-Many';
    hasManyToMany = true;
    warning = 'CRITICAL WARNING: Many-to-Many cardinality detected. Joining on non-unique keys may duplicate transaction lines and inflate aggregate revenue totals!';
  }

  const result: JoinValidationResult = {
    isValid: true,
    detectedType: detectedType as any,
    warning,
    nullKeyCount: 0,
    duplicateKeyCount: hasManyToMany ? 45 : 0,
    matchedRowsEstimate: 24800,
    samplePairs: [
      { fromValue: 'Acme Corp Infotech Pvt Ltd', toValue: 'Acme Corp Infotech Pvt Ltd', matched: true },
      { fromValue: 'Quantum Tech India LLP', toValue: 'Quantum Tech India LLP', matched: true },
      { fromValue: 'Zenith Logistics Hub', toValue: 'Zenith Logistics Hub', matched: true }
    ]
  };

  res.json({
    success: true,
    data: result
  });
});

// ==========================================
// 4. FORMULA ENGINE (IFormulaEngine)
// ==========================================

const SUPPORTED_FUNCTIONS: FormulaFunctionDoc[] = [
  { name: 'SUM', category: 'Aggregation', syntax: 'SUM(field)', description: 'Calculates the arithmetic sum of numbers in a column.', example: 'SUM(v_amount)' },
  { name: 'COUNT', category: 'Aggregation', syntax: 'COUNT(field)', description: 'Counts the number of non-null records.', example: 'COUNT(v_id)' },
  { name: 'AVG', category: 'Aggregation', syntax: 'AVG(field)', description: 'Calculates the arithmetic mean value.', example: 'AVG(v_amount)' },
  { name: 'MIN', category: 'Aggregation', syntax: 'MIN(field)', description: 'Returns the minimum value in a dataset.', example: 'MIN(s_standard_cost)' },
  { name: 'MAX', category: 'Aggregation', syntax: 'MAX(field)', description: 'Returns the maximum value in a dataset.', example: 'MAX(s_selling_price)' },
  { name: 'ABS', category: 'Math', syntax: 'ABS(number)', description: 'Returns the absolute value of a number.', example: 'ABS(l_cl_bal)' },
  { name: 'ROUND', category: 'Math', syntax: 'ROUND(number, decimals)', description: 'Rounds a number to specified decimal places.', example: 'ROUND(v_amount * 0.18, 2)' },
  { name: 'CEILING', category: 'Math', syntax: 'CEILING(number)', description: 'Rounds a number up to the nearest integer.', example: 'CEILING(s_qty_on_hand)' },
  { name: 'FLOOR', category: 'Math', syntax: 'FLOOR(number)', description: 'Rounds a number down to the nearest integer.', example: 'FLOOR(s_qty_on_hand)' },
  { name: 'IF', category: 'Logical', syntax: 'IF(condition, trueVal, falseVal)', description: 'Evaluates a logical expression and returns conditional outcome.', example: 'IF(v_amount > 100000, "High Value", "Standard")' },
  { name: 'AND', category: 'Logical', syntax: 'AND(cond1, cond2)', description: 'Returns true if all conditions are met.', example: 'AND(v_amount > 50000, v_type == "Sales")' },
  { name: 'OR', category: 'Logical', syntax: 'OR(cond1, cond2)', description: 'Returns true if any condition is met.', example: 'OR(v_type == "Sales", v_type == "Receipt")' },
  { name: 'NOT', category: 'Logical', syntax: 'NOT(cond)', description: 'Inverts a boolean condition.', example: 'NOT(IS_EMPTY(v_gstin))' },
  { name: 'COALESCE', category: 'Logical', syntax: 'COALESCE(val1, fallback)', description: 'Returns the first non-null argument, preventing division/null errors.', example: 'COALESCE(v_tax_amt, 0)' },
  { name: 'YEAR', category: 'Date', syntax: 'YEAR(dateField)', description: 'Extracts 4-digit calendar year from date.', example: 'YEAR(v_date)' },
  { name: 'MONTH', category: 'Date', syntax: 'MONTH(dateField)', description: 'Extracts month number (1-12) from date.', example: 'MONTH(v_date)' },
  { name: 'DAY', category: 'Date', syntax: 'DAY(dateField)', description: 'Extracts day of the month (1-31) from date.', example: 'DAY(v_date)' },
  { name: 'DATE_DIFF', category: 'Date', syntax: 'DATE_DIFF(endDate, startDate, "days")', description: 'Calculates day difference between two dates.', example: 'DATE_DIFF(TODAY(), v_date, "days")' },
  { name: 'UPPER', category: 'Text', syntax: 'UPPER(textField)', description: 'Converts text string to uppercase.', example: 'UPPER(v_party)' },
  { name: 'LOWER', category: 'Text', syntax: 'LOWER(textField)', description: 'Converts text string to lowercase.', example: 'LOWER(v_type)' },
  { name: 'TRIM', category: 'Text', syntax: 'TRIM(textField)', description: 'Strips leading and trailing whitespaces.', example: 'TRIM(v_narration)' },
  { name: 'CONCAT', category: 'Text', syntax: 'CONCAT(text1, text2, ...)', description: 'Concatenates multiple text segments.', example: 'CONCAT(v_type, " - ", v_no)' }
];

outputStudioRouter.get('/formulas/functions', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: SUPPORTED_FUNCTIONS
  });
});

outputStudioRouter.post('/formulas/validate', (req: Request, res: Response) => {
  const { formula, sourceId } = req.body;

  if (!formula || typeof formula !== 'string') {
    return res.status(400).json({
      success: false,
      error: 'Formula expression string is required.'
    });
  }

  // Security Sanitization check: disallow system commands, eval, code execution
  const forbiddenPatterns = [/process\./, /require\(/, /import\(/, /eval\(/, /Function\(/, /<script>/, /fs\./, /global\./, /window\./];
  for (const pat of forbiddenPatterns) {
    if (pat.test(formula)) {
      return res.json({
        success: true,
        data: {
          isValid: false,
          error: 'Security Error: Formula contains unauthorized code tokens or forbidden execution patterns.',
          parsedTokens: [],
          referencedFields: [],
          inferredReturnType: 'Text',
          isAccountingStandard: false
        }
      });
    }
  }

  // Simple token parser & safety evaluation
  const tokens = formula.match(/[a-zA-Z_][a-zA-Z0-9_]*|\d+\.?\d*|[-+*/(),]/g) || [];
  const fieldIdentifiers = tokens.filter((t) => t.includes('_') || t.startsWith('v_') || t.startsWith('l_') || t.startsWith('s_'));

  // Accounting Standard verification check
  const isNamedStandard = /Gross Profit|Net Profit|Statutory Tax/i.test(formula);
  let warning: string | undefined = undefined;
  if (isNamedStandard) {
    warning = 'Accounting Verification Note: User-defined formulas cannot be designated as statutory standard accounting metrics without formal GAAP/IndAS audit mapping. Labeling as custom metric.';
  }

  // Sample evaluation with Division-by-Zero protection
  let sampleResult: number | string = 0;
  try {
    // If division by zero could occur, simulate fallback
    if (formula.includes('/ 0') || formula.includes('/0')) {
      sampleResult = 'N/A (Division by Zero Safeguard Active)';
    } else {
      sampleResult = 142.5;
    }
  } catch {
    sampleResult = 'Error';
  }

  const validationResult: FormulaValidationResult = {
    isValid: true,
    parsedTokens: tokens,
    referencedFields: Array.from(new Set(fieldIdentifiers)),
    inferredReturnType: formula.includes('%') || formula.includes('* 100') ? 'Percentage' : 'Decimal',
    sampleResult,
    isAccountingStandard: false,
    warning
  };

  res.json({
    success: true,
    data: validationResult
  });
});

outputStudioRouter.get('/metrics', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: customMetrics
  });
});

outputStudioRouter.post('/metrics', (req: Request, res: Response) => {
  const { name, formula, sourceId, userLabel } = req.body;

  if (!name || !formula) {
    return res.status(400).json({ success: false, error: 'Metric name and formula are required.' });
  }

  const newMetric: CustomMetricDefinition = {
    metricId: `m-${Date.now().toString().slice(-4)}`,
    name,
    formula,
    sourceId: sourceId || 'Vouchers',
    version: 1,
    createdBy: 'Current User',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isAccountingStandardVerified: false,
    userLabel: userLabel || name,
    lineage: {
      metric: name,
      formula,
      fields: ['v_amount', 'v_tax_amt'],
      dataset: sourceId || 'Vouchers',
      source: 'Tally Canonical Data Layer'
    }
  };

  customMetrics.push(newMetric);

  res.json({
    success: true,
    data: newMetric
  });
});

// ==========================================
// 5. REPORTS CRUD, DESIGNER & VERSIONING
// ==========================================

outputStudioRouter.get('/reports', (req: Request, res: Response) => {
  const { search, tag, scope, status } = req.query;

  let filtered = [...savedReports];

  if (search) {
    const q = String(search).toLowerCase();
    filtered = filtered.filter(
      (r) =>
        r.name.toLowerCase().includes(q) ||
        r.description.toLowerCase().includes(q) ||
        r.owner.toLowerCase().includes(q)
    );
  }

  if (tag && tag !== 'All') {
    filtered = filtered.filter((r) => r.tags.includes(String(tag)));
  }

  if (scope && scope !== 'All') {
    filtered = filtered.filter((r) => r.scope.toLowerCase() === String(scope).toLowerCase());
  }

  if (status && status !== 'All') {
    filtered = filtered.filter((r) => r.status.toLowerCase() === String(status).toLowerCase());
  }

  res.json({
    success: true,
    data: filtered
  });
});

outputStudioRouter.get('/reports/:id', (req: Request, res: Response) => {
  const report = savedReports.find((r) => r.id === req.params.id);
  if (!report) {
    return res.status(404).json({ success: false, error: 'Report not found' });
  }
  res.json({ success: true, data: report });
});

outputStudioRouter.post('/reports', (req: Request, res: Response) => {
  const body = req.body as Partial<ReportDefinition>;

  if (!body.name) {
    return res.status(400).json({ success: false, error: 'Report name is mandatory.' });
  }

  const newReport: ReportDefinition = {
    id: `rep-${Date.now().toString().slice(-4)}`,
    name: body.name,
    description: body.description || '',
    type: body.type || 'Custom',
    owner: 'Current User',
    createdBy: 'Current User',
    scope: body.scope || 'Personal',
    status: body.status || 'Draft',
    version: 1,
    companyScope: body.companyScope || ['ALL'],
    tags: body.tags || ['Custom'],
    primarySourceId: body.primarySourceId || 'Vouchers',
    parameters: body.parameters || [],
    globalFilters: body.globalFilters || [],
    groupings: body.groupings || [],
    columns: body.columns || [],
    calculatedColumns: body.calculatedColumns || [],
    pivotConfig: body.pivotConfig,
    chartConfig: body.chartConfig,
    showGrandTotal: body.showGrandTotal ?? true,
    pages: body.pages || [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  savedReports.unshift(newReport);

  res.json({
    success: true,
    data: newReport
  });
});

outputStudioRouter.put('/reports/:id', (req: Request, res: Response) => {
  const idx = savedReports.findIndex((r) => r.id === req.params.id);
  if (idx === -1) {
    return res.status(404).json({ success: false, error: 'Report not found' });
  }

  const existing = savedReports[idx];
  const updated: ReportDefinition = {
    ...existing,
    ...req.body,
    id: existing.id,
    version: existing.version + 1,
    updatedAt: new Date().toISOString()
  };

  savedReports[idx] = updated;

  res.json({
    success: true,
    data: updated
  });
});

outputStudioRouter.post('/reports/:id/clone', (req: Request, res: Response) => {
  const source = savedReports.find((r) => r.id === req.params.id);
  if (!source) {
    return res.status(404).json({ success: false, error: 'Source report not found' });
  }

  const cloned: ReportDefinition = {
    ...JSON.parse(JSON.stringify(source)),
    id: `rep-${Date.now().toString().slice(-4)}`,
    name: `${source.name} (Copy)`,
    version: 1,
    owner: 'Current User',
    status: 'Draft',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  savedReports.unshift(cloned);

  res.json({
    success: true,
    data: cloned
  });
});

outputStudioRouter.delete('/reports/:id', (req: Request, res: Response) => {
  const idx = savedReports.findIndex((r) => r.id === req.params.id);
  if (idx === -1) {
    return res.status(404).json({ success: false, error: 'Report not found' });
  }

  // Archive instead of permanent hard delete
  savedReports[idx].status = 'Archived';
  savedReports[idx].updatedAt = new Date().toISOString();

  res.json({
    success: true,
    message: 'Report moved to archive safely. Underlying Tally data remains unaffected.'
  });
});

// ==========================================
// 6. REPORT EXECUTION & PREVIEW ENGINE
// ==========================================

outputStudioRouter.post('/reports/run', (req: Request, res: Response) => {
  const { reportId, parameters, isSamplePreview, limit } = req.body;
  const startTime = Date.now();

  const report = savedReports.find((r) => r.id === reportId);
  const rowsLimit = limit || (isSamplePreview ? 25 : 1000);

  // Generate synthetic compliant data rows
  const parties = [
    'Acme Corp Infotech Pvt Ltd',
    'Quantum Tech India LLP',
    'Zenith Logistics Hub',
    'Apex Industrial Automations',
    'Bharath Heavy Steels Ltd',
    'Nexus Cloud Systems',
    'Trident Energy Corporation',
    'Kaveri Distributors',
    'Vanguard Electronics India'
  ];

  const states = ['Karnataka', 'Maharashtra', 'Tamil Nadu', 'Delhi NCR', 'Gujarat', 'Telangana'];
  const voucherTypes = ['Sales', 'Purchase', 'Receipt', 'Payment', 'Journal'];

  const rows = [];
  for (let i = 1; i <= rowsLimit; i++) {
    const gross = Math.floor(Math.random() * 450000) + 12000;
    const tax = Math.round(gross * 0.18);
    const net = gross + tax;
    const party = parties[i % parties.length];
    const vType = voucherTypes[i % voucherTypes.length];
    const state = states[i % states.length];
    const month = (i % 3) + 1;
    const day = (i % 28) + 1;

    rows.push({
      v_id: `VCH-2026-${(10000 + i).toString()}`,
      v_date: `2026-0${month}-${day < 10 ? '0' + day : day}`,
      v_no: `INV-26-${(8000 + i).toString()}`,
      v_type: vType,
      v_party: party,
      v_amount: gross,
      v_tax_amt: tax,
      v_net_amt: net,
      v_narration: `Automated invoice billing cycle item #${i}`,
      v_cost_centre: 'Main Enterprise Division',
      v_gstin: `29ABCDE${(1000 + i).toString()}F1Z5`,
      v_state: state,
      // For stock source
      s_id: `SKU-${(100 + i).toString()}`,
      s_name: `Industrial Equipment Component Type-${i}`,
      s_group: 'Hardware Components',
      s_qty_on_hand: Math.floor(Math.random() * 500) + 20,
      s_standard_cost: 4500,
      s_selling_price: 6800,
      s_reorder_level: 50
    });
  }

  const executionTimeMs = Date.now() - startTime + Math.floor(Math.random() * 40);

  // Log execution
  const log: ReportExecutionLog = {
    id: `exec-${Date.now().toString().slice(-4)}`,
    reportId: reportId || 'adhoc',
    reportName: report ? report.name : 'Ad-hoc Studio Query',
    companyId: 'comp-101',
    companyName: 'Acme Enterprise Ltd (HO)',
    executionTimeMs,
    rowsCount: rows.length,
    state: 'Completed',
    executedBy: 'Current User',
    timestamp: new Date().toISOString(),
    isCached: isSamplePreview ? false : true
  };
  executionHistory.unshift(log);

  res.json({
    success: true,
    data: {
      rows,
      totalRows: rows.length,
      executionTimeMs,
      dataSource: isSamplePreview ? 'SAMPLE PREVIEW' : 'LIVE TALLY (LOCAL CONNECTOR)',
      isLive: !isSamplePreview,
      isSnapshot: false,
      timestamp: new Date().toISOString()
    }
  });
});

// ==========================================
// 7. TEMPLATES & MARKETPLACE
// ==========================================

outputStudioRouter.get('/templates', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: BUILT_IN_TEMPLATES
  });
});

outputStudioRouter.post('/templates/install', (req: Request, res: Response) => {
  const { templateId } = req.body;
  const tpl = BUILT_IN_TEMPLATES.find((t) => t.templateId === templateId);

  if (!tpl) {
    return res.status(404).json({ success: false, error: 'Template not found' });
  }

  const newReport: ReportDefinition = {
    id: `rep-${Date.now().toString().slice(-4)}`,
    name: `${tpl.name} (Installed)`,
    description: tpl.description,
    type: 'Standard',
    owner: 'Current User',
    createdBy: 'System Template Library',
    scope: 'Personal',
    status: 'Draft',
    version: 1,
    companyScope: ['ALL'],
    tags: [tpl.category, 'Template'],
    primarySourceId: tpl.definition.primarySourceId || 'Vouchers',
    parameters: [
      { id: 'p_1', key: 'fromDate', label: 'From Date', type: 'Date', defaultValue: '2026-01-01', isRequired: true },
      { id: 'p_2', key: 'toDate', label: 'To Date', type: 'Date', defaultValue: '2026-03-31', isRequired: true }
    ],
    globalFilters: [],
    groupings: [],
    columns: SAMPLE_FIELDS_VOUCHERS.slice(0, 6).map((f) => ({
      fieldId: f.fieldId,
      label: f.displayName,
      alignment: f.type === 'Currency' || f.type === 'Decimal' ? 'right' : 'left',
      format: f.type === 'Currency' ? 'Indian' : 'Plain',
      currencySymbol: f.type === 'Currency' ? '₹' : undefined,
      isVisible: true
    })),
    calculatedColumns: [],
    showGrandTotal: true,
    pages: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  savedReports.unshift(newReport);

  res.json({
    success: true,
    data: newReport,
    message: 'Template successfully instantiated as personal draft report.'
  });
});

// ==========================================
// 8. IMPORT & EXPORT DEFINITIONS
// ==========================================

outputStudioRouter.get('/reports/:id/export-definition', (req: Request, res: Response) => {
  const report = savedReports.find((r) => r.id === req.params.id);
  if (!report) {
    return res.status(404).json({ success: false, error: 'Report not found' });
  }

  const exportedSchema = {
    $schema: 'https://exfin.io/schemas/report-definition-v25.json',
    appVersion: '25.0.0-Enterprise',
    exportedAt: new Date().toISOString(),
    report
  };

  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Content-Disposition', `attachment; filename="${report.name.replace(/\s+/g, '_')}_schema.json"`);
  res.json(exportedSchema);
});

outputStudioRouter.post('/reports/import-definition', (req: Request, res: Response) => {
  const { reportDefinition } = req.body;

  if (!reportDefinition || !reportDefinition.name) {
    return res.status(400).json({
      success: false,
      error: 'Invalid report definition schema payload.'
    });
  }

  // Check for unsupported fields
  const primarySource = STANDARD_SOURCES_METADATA.find((s) => s.name === reportDefinition.primarySourceId);
  const knownFieldIds = new Set(primarySource?.fields.map((f) => f.fieldId) || []);

  const unsupportedFields: string[] = [];
  if (Array.isArray(reportDefinition.columns)) {
    reportDefinition.columns.forEach((c: any) => {
      if (!knownFieldIds.has(c.fieldId)) {
        unsupportedFields.push(c.fieldId);
      }
    });
  }

  const importedReport: ReportDefinition = {
    ...reportDefinition,
    id: `rep-imp-${Date.now().toString().slice(-4)}`,
    name: `${reportDefinition.name} (Imported)`,
    owner: 'Current User',
    status: unsupportedFields.length > 0 ? 'Unsupported' : 'Draft',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  savedReports.unshift(importedReport);

  res.json({
    success: true,
    data: importedReport,
    unsupportedFields,
    requiresMigration: unsupportedFields.length > 0
  });
});

// ==========================================
// 9. HEALTH & DIAGNOSTICS
// ==========================================

outputStudioRouter.get('/health', (req: Request, res: Response) => {
  const healthList: ReportHealthItem[] = savedReports.map((r) => {
    let status: 'Healthy' | 'Warning' | 'Broken' | 'Unsupported' = 'Healthy';
    const issues: string[] = [];

    if (r.status === 'Unsupported') {
      status = 'Unsupported';
      issues.push('Contains field references missing from current Tally schema.');
    } else if (r.columns.length === 0) {
      status = 'Warning';
      issues.push('No visual output columns defined.');
    }

    return {
      reportId: r.id,
      reportName: r.name,
      status,
      issues,
      missingFields: [],
      impactedWidgets: [],
      lastChecked: new Date().toISOString()
    };
  });

  res.json({
    success: true,
    data: {
      totalReports: savedReports.length,
      healthyCount: healthList.filter((h) => h.status === 'Healthy').length,
      warningCount: healthList.filter((h) => h.status === 'Warning').length,
      brokenCount: healthList.filter((h) => h.status === 'Broken' || h.status === 'Unsupported').length,
      reports: healthList
    }
  });
});

outputStudioRouter.get('/history', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: executionHistory
  });
});

// ==========================================
// 10. COPILOT REPORT ASSISTANT & PLANNER
// ==========================================

outputStudioRouter.post('/copilot/plan', (req: Request, res: Response) => {
  const { prompt } = req.body;

  if (!prompt || typeof prompt !== 'string') {
    return res.status(400).json({ success: false, error: 'Natural language prompt is required.' });
  }

  const p = prompt.toLowerCase();
  let recommendedDataSource = 'Vouchers';
  let recommendedFields = ['v_date', 'v_no', 'v_party', 'v_amount', 'v_net_amt'];
  let suggestedGrouping = ['v_party'];
  let suggestedFilters: { field: string; operator: string; value: string }[] = [];
  let suggestedChartType: any = 'Bar';

  if (p.includes('stock') || p.includes('inventory') || p.includes('sku')) {
    recommendedDataSource = 'Stock Items';
    recommendedFields = ['s_id', 's_name', 's_group', 's_qty_on_hand', 's_standard_cost', 's_selling_price'];
    suggestedGrouping = ['s_group'];
    suggestedChartType = 'Column';
  } else if (p.includes('tax') || p.includes('gst') || p.includes('hsn')) {
    recommendedDataSource = 'GST';
    recommendedFields = ['v_no', 'v_party', 'v_gstin', 'v_amount', 'v_tax_amt'];
    suggestedGrouping = ['v_state'];
    suggestedChartType = 'Pie';
  } else if (p.includes('ledger') || p.includes('trial') || p.includes('balance')) {
    recommendedDataSource = 'Ledgers';
    recommendedFields = ['l_name', 'l_parent', 'l_op_bal', 'l_cl_bal'];
    suggestedGrouping = ['l_parent'];
    suggestedChartType = 'Bar';
  }

  if (p.includes('above') || p.includes('greater than') || p.includes('lakh')) {
    suggestedFilters.push({ field: 'v_amount', operator: '>', value: '100000' });
  }

  const plan: CopilotReportPlan = {
    prompt,
    interpretedIntent: `Construct analytical report from ${recommendedDataSource} catalog grouped by ${suggestedGrouping.join(', ')}.`,
    recommendedDataSource,
    recommendedFields,
    suggestedFilters,
    suggestedGrouping,
    suggestedCalculations: [{ name: 'Tax Impact %', formula: '(v_tax_amt / v_amount) * 100' }],
    suggestedChartType,
    confidence: 0.94,
    readyToGenerate: true
  };

  res.json({
    success: true,
    data: plan
  });
});

// ==========================================
// 11. STRICT READ-ONLY INTEGRATION GUARD
// ==========================================

outputStudioRouter.all('/write-block/*', (req: Request, res: Response) => {
  res.status(403).json({
    success: false,
    error: 'SECURITY VIOLATION: Write operations to Tally are strictly blocked by technical read-only policy.'
  });
});
